CREATE TABLE
  `posts` (
    `id` varchar(36) NOT NULL COMMENT 'UUID',
    `creatorId` varchar(10) NOT NULL,
    `title` varchar(200) NOT NULL,
    `description` text,
    `fileType` enum(
      'game',
      'app',
      'document',
      'audio',
      'video',
      'other'
    ) NOT NULL DEFAULT 'other',
    `fileSize` bigint DEFAULT NULL COMMENT 'bytes',
    `filePath` varchar(500) DEFAULT NULL COMMENT 'S3 key or local path in drop-files/',
    `originalFileName` varchar(255) DEFAULT NULL,
    `mimeType` varchar(100) DEFAULT NULL,
    `thumbnailUrl` varchar(500) DEFAULT NULL,
    `trailerUrl` varchar(500) DEFAULT NULL,
    `mature` tinyint(1) NOT NULL DEFAULT '0',
    `tags` text COMMENT '["game","rpg","indie"]',
    `totalDownloads` int NOT NULL DEFAULT '0',
    `totalRevenue` bigint NOT NULL DEFAULT '0' COMMENT 'Credits earned from post-drop sales',
    `avgRating` decimal(4, 2) DEFAULT NULL COMMENT '0-100 community quality rating',
    `reviewCount` int NOT NULL DEFAULT '0',
    `likeCount` int NOT NULL DEFAULT '0',
    `dislikeCount` int NOT NULL DEFAULT '0',
    `status` enum(
      'draft',
      'pending',
      'active',
      'dropped',
      'expired',
      'removed',
      'hidden',
      'boosted'
    ) NOT NULL DEFAULT 'draft',
    `isPublic` tinyint(1) NOT NULL DEFAULT '1',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `lastContributionTime` datetime DEFAULT NULL,
    `views` int DEFAULT NULL,
    `quality` int DEFAULT NULL,
    `effort` int DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_creatorId` (`creatorId`),
    KEY `idx_status` (`status`),
    KEY `idx_created_at` (`created_at`),
    CONSTRAINT `fk_drops_creator` FOREIGN KEY (`creatorId`) REFERENCES `userData` (`id`) ON DELETE CASCADE
  ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci